/**
 * 
 */
package com.mo.springtest.domain;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * @author Admin
 *
 */
@Entity
@Table(name = "products")
public class Product {

	// An autogenerated id (unique for each product in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	
	private String name;
	private double cost;
	@OneToOne(cascade=CascadeType.PERSIST)
	@JoinColumn(name="CATEGORY_ID", nullable=false)
	private Category category;
	
	public Product() { }
	
	public Product(String name, double cost, Category category) {
		this.name = name;
		this.cost = cost;
		this.category = category;
	}
	
	public double getNetCost(){
		
		return cost - category.getSalesTax() * cost;
	}
	
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public double getCost() {
		return cost;
	}
	public void setCost(double cost) {
		this.cost = cost;
	}
	public Category getCategory() {
		return category;
	}
	public void setCategory(Category category) {
		this.category = category;
	}
	
	public String print() {
		return getName() + "       " + getCategory().getName()  + "      " + getCost()  + "          "+ getCategory().getSalesTaxString()  + "        "+ getNetCost();
	}
	

}
